"""empty message

Revision ID: 239b18ec62db
Revises: 
Create Date: 2019-09-16 10:32:13.478172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '239b18ec62db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('cgpa', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('college_code', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('dob', sa.String(length=30), nullable=True))
    op.add_column('students', sa.Column('location', sa.String(length=30), nullable=True))
    op.add_column('students', sa.Column('studentname', sa.String(length=30), nullable=True))
    op.drop_column('students', 'amount')
    op.drop_column('students', 'ItemId')
    op.drop_column('students', 'createdAt')
    op.drop_column('students', 'studentQty')
    op.drop_column('students', 'studentDate')
    op.drop_column('students', 'updatedAt')
    op.drop_column('students', 'studentStatus')
    op.drop_column('students', 'walletId')
    op.drop_column('students', 'customerId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('customerId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('walletId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('studentStatus', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('students', sa.Column('updatedAt', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('students', sa.Column('studentDate', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('students', sa.Column('studentQty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('createdAt', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('students', sa.Column('ItemId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('students', 'studentname')
    op.drop_column('students', 'location')
    op.drop_column('students', 'dob')
    op.drop_column('students', 'college_code')
    op.drop_column('students', 'cgpa')
    # ### end Alembic commands ###
